development:
  adapter: jdbcpostgresql
  host: localhost
  port: 5432
  username: boxgrinder
  password: boxgrinder
  database: boxgrinder_development
  encoding: utf8

test:
  adapter: jdbcsqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: jdbcpostgresql
  host: localhost
  port: 5432
  username: boxgrinder
  password: boxgrinder
  database: boxgrinder_production
  encoding: utf8
